name: Enforce PR labels
on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize', 'labeled', 'unlabeled' ]
jobs:
  enforce-label:
    name: Enforce PR labels
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "feature,bug,optimize,testing,unit-test,workflows,lint,ci/cd,refactor,documentation,performance,security"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['feature','bug','optimize','testing','unit-test','workflows','lint',ci/cd','refactor','documentation','performance','security']"
          BANNED_LABELS: "banned,wontfix,obsolete,invalid,question,duplicate,try-your-luck,support-needed,low-priority"